# --- CẤU HÌNH OCR NHÓM 11 (KIẾN TRÚC SEQ2SEQ - ĐÃ FIX VOCAB) ---

aug:
  image_aug: true
  masked_language_model: false # Seq2Seq không dùng cái này, tắt đi cho nhẹ

backbone: vgg19_bn

cnn:
  hidden: 256
  ks:
  - [2, 2]
  - [2, 2]
  - [2, 1]
  - [2, 1]
  - [1, 1]
  pretrained: true
  ss:
  - [2, 2]
  - [2, 2]
  - [2, 1]
  - [2, 1]
  - [1, 1]

dataloader:
  num_workers: 3
  pin_memory: true

dataset:
  data_root: ./img/
  image_height: 32
  image_max_width: 512
  image_min_width: 32
  name: data
  train_annotation: annotation_train.txt
  valid_annotation: annotation_val_small.txt
  # QUAN TRỌNG: Đây là bộ Vocab chuẩn của VietOCR Seq2Seq
  vocab: 'aAàÀảẢãÃáÁạẠăĂằẰẳẲẵẴắẮặẶâÂầẦẩẨẫẪấẤậẬbBcCdDđĐeEèÈẻẺẽẼéÉẹẸêÊềỀểỂễỄếẾệỆfFgGhHiIìÌỉỈĩĨíÍịỊjJkKlLmMnNoOòÒỏỎõÕóÓọỌôÔồỒổỔỗỖốỐộỘơƠờỜởỞỡỠớỚợỢpPqQrRsStTuUùÙủỦũŨúÚụỤưƯừỪửỬữỮứỨựỰvVwWxXyYỳỲỷỶỹỸýÝỵỴzZ0123456789!"#$%&''()*+,-./:;<=>?@[\]^_`{|}~ '

device: cpu 

optimizer:
  max_lr: 0.0003
  pct_start: 0.1

predictor:
  beamsearch: false

seq_modeling: seq2seq

seq2seq:
  encoder_hidden: 256
  decoder_hidden: 256
  img_channel: 256
  decoder_embedded: 256
  dropout: 0.1

trainer:
  batch_size: 32
  checkpoint: ./checkpoint/seq2seq_ocr_nhom11.pth
  export: ./weights/seq2seq_ocr_nhom11.pth
  iters: 15000
  log: ./train.log
  metrics: 1000
  print_every: 200
  valid_every: 1000

# Bộ từ vựng ngoài cũng phải khớp hệt như trong dataset.vocab
vocab: 'aAàÀảẢãÃáÁạẠăĂằẰẳẲẵẴắẮặẶâÂầẦẩẨẫẪấẤậẬbBcCdDđĐeEèÈẻẺẽẼéÉẹẸêÊềỀểỂễỄếẾệỆfFgGhHiIìÌỉỈĩĨíÍịỊjJkKlLmMnNoOòÒỏỎõÕóÓọỌôÔồỒổỔỗỖốỐộỘơƠờỜởỞỡỠớỚợỢpPqQrRsStTuUùÙủỦũŨúÚụỤưƯừỪửỬữỮứỨựỰvVwWxXyYỳỲỷỶỹỸýÝỵỴzZ0123456789!"#$%&''()*+,-./:;<=>?@[\]^_`{|}~ '
weights: ./seq2seq_ocr_nhom11.pth